IF EXISTS(SELECT * FROM sys.databases WHERE name='BaseDeDonnees_TP2')
BEGIN
	DROP DATABASE BaseDeDonnees_TP2
END

CREATE DATABASE BaseDeDonnees_TP2
GO
USE BaseDeDonnees_TP2
GO

EXEC sp_configure filestream_access_level, 2 RECONFIGURE

ALTER DATABASE BaseDeDonnees_TP2
ADD FILEGROUP FG_Images_2185802 CONTAINS FILESTREAM;
GO
ALTER DATABASE BaseDeDonnees_TP2
ADD FILE (
	NAME = FG_Images_2185802,
	FILENAME = 'C:\EspaceLabo\FG_Images_2185802'
)
TO FILEGROUP FG_Images_2185802
GO